const express=require('express')
const router=express.Router()
const addvalidate =require('../middleware/addmiddleware')
const verifytoken =require('../middleware/auth')
const upload=require('../middleware/upload')
const {addStudent}=require('../Controller/addStudent')
const {getStudent,getProfile,userDelete,editUser,updateUser}=require('../Controller/addStudent')
router.post('/addstudent',verifytoken,upload.single('img'),addvalidate,addStudent)
router.get('/studentlist',verifytoken,getStudent)
router.put('/update/:id',verifytoken,upload.single('img'),updateUser)
router.get('/edit/:id',verifytoken,editUser)
router.get('/studentprofile',verifytoken,getProfile)
router.delete('/delete/:id',verifytoken,userDelete)
module.exports=router